#!/usr/bin/env python3
"""Copies the native sources the Rust crate needs into rust/native/.

Cargo can only publish files inside the package directory, so a crate whose
build.rs compiles the C++ core cannot reach up to the repository root once it is
published. This script stages the sources the crate needs inside rust/native/,
which is what `cargo publish` then includes.

Run before `cargo package` or `cargo publish`:

    python3 scripts/vendor_rust_sources.py

The directory is generated and gitignored. build.rs uses it when present and
falls back to the repository root for in-repo builds, so a normal `cargo test`
in a checkout needs no vendoring step.
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
VENDOR_DIR = ROOT / "rust" / "native"

# Files and directories the CMake build needs, relative to the repository root.
# avioflow/bin is deliberately excluded: those are examples and tests, and the
# crate configures with -DBUILD_TESTS=OFF -DENABLE_BINARY=OFF.
VENDORED_PATHS = (
    "CMakeLists.txt",
    "version.txt",
    "cmake",
    "avioflow/include",
    "avioflow/core",
)

# Copied to rust/ rather than rust/native/, because Cargo only includes files at
# the package root. Copying keeps the repository LICENSE the single source of
# truth instead of maintaining a second copy under rust/.
ROOT_FILES_FOR_CRATE = ("LICENSE",)


def main() -> None:
    missing = [name for name in VENDORED_PATHS if not (ROOT / name).exists()]
    if missing:
        raise SystemExit(f"Cannot vendor, missing from the repository: {missing}")

    if VENDOR_DIR.exists():
        shutil.rmtree(VENDOR_DIR)
    VENDOR_DIR.mkdir(parents=True)

    for name in VENDORED_PATHS:
        source = ROOT / name
        target = VENDOR_DIR / name
        target.parent.mkdir(parents=True, exist_ok=True)
        if source.is_dir():
            # __pycache__ and build leftovers would bloat the published crate.
            shutil.copytree(
                source,
                target,
                ignore=shutil.ignore_patterns("__pycache__", "*.pyc", "build", "build_*"),
            )
        else:
            shutil.copy2(source, target)

    for name in ROOT_FILES_FOR_CRATE:
        source = ROOT / name
        if not source.exists():
            raise SystemExit(f"Cannot vendor, missing from the repository: {name}")
        shutil.copy2(source, ROOT / "rust" / name)

    # A marker so build.rs can tell a complete vendor tree from a stale one.
    (VENDOR_DIR / "VENDORED").write_text(
        "Generated by scripts/vendor_rust_sources.py. Do not edit by hand.\n",
        encoding="utf-8",
    )

    file_count = sum(1 for path in VENDOR_DIR.rglob("*") if path.is_file())
    total_bytes = sum(path.stat().st_size for path in VENDOR_DIR.rglob("*") if path.is_file())
    print(
        f"Vendored {file_count} files ({total_bytes / 1024:.0f} KiB) into "
        f"{VENDOR_DIR.relative_to(ROOT)}"
    )


if __name__ == "__main__":
    sys.exit(main())
